### ISSUE TITLE
DID resolving not working with did from installation instructions

### ISSUE THREAD

**Issue by mahoekst** [decentralized-identity/ion#101]
When i try this http://localhost:3000/identifiers/did:ion:test:EiDu6ZLMupgrqTQJjOki6xGEQZ9iUslA5ro_LzMXEXEoCA

I get the following in the log files:
Handling resolution request for: did:ion:test:EiDu6ZLMupgrqTQJjOki6xGEQZ9iUslA5ro_LzMXEXEoCA...
Resolving DID unique suffix 'EiDu6ZLMupgrqTQJjOki6xGEQZ9iUslA5ro_LzMXEXEoCA'...

curl gives me a 404
Does anybody have a good test DID I can use to see if my node is working?

**Comment by downTheFallLine** [comment]
I can repro this same issue.

**Comment by TomCJones** [comment]
i get the following. Also not sure what the CRUD commands for ION are supposed to be. Is anyone actually running ION?

**Comment by thehenrytsai** [comment]
This is caused by js-IPFS not being able to download DID data. We have since contacted the core IPFS team and they adviced us to use go-IPFS directly because go-IPFS directly participates with the DHT while js-IPFS doesn't thus making js-IPFS far less reliable for content resolution.

We are pushing out v0.10.0 as we speak and with this release it deprecates the the ION IPFS service entirely in favor of using go-IPFS directly. This should resolve the issue you are seeing. Note ION genesis block has been moved since v0.9.0, thus test DID the install guide has also been updated (EiBFsUlzmZ3zJtSFeQKwJNtngjmB51ehMWWDuptf9b4Bag for testnet) but should be resolvable.

Fell free to open new issues if you are still having problems after running v0.10.0, thanks again for your interest in trying ION prior to official v1.
