### ISSUE TITLE
Unresolvable test DIDs

### ISSUE THREAD

**Issue by peacekeeper** [decentralized-identity/ion#177]
_(Sorry for cross-posting from https://github.com/decentralized-identity/sidetree/issues/1071, but got no answer there.)_

Quick questions about the current state of did:ion....

1. We created a test DID `did:ion:test:EiBISbrXlYeXjxQ7uf2tQoE0dUxpmkpJMovhxCGKKGycEg`, which is resolvable via our local ION node, but not resolvable via `curl -X GET https://beta.discover.did.microsoft.com/1.0/identifiers/did:ion:test:EiBISbrXlYeXjxQ7uf2tQoE0dUxpmkpJMovhxCGKKGycEg`.
2. Is the Universal Resolver driver for `did:ion` up to date? It says last updated 4 months ago. See https://hub.docker.com/r/identityfoundation/driver-did-ion.
3. Any recommendation for a "good did:ion example DID" that we can display in the frontend at https://dev.uniresolver.io/?

**Comment by csuwildcat** [comment]
@thehenrytsai @isaacJChen  ^

**Comment by thehenrytsai** [comment]
@peacekeeper,

Thanks for the question:

1. The `beta.discover.did.microsoft.com` endpoint only resolves mainnet DIDs now that ION has hit v1. That being said, we can resolve the testnet DID that you've created from our dev environment targeting testnet. To prove it here is the service property resolved:
```json
"service": [
            {
                "id": "#test1",
                "type": "agent",
                "serviceEndpoint": "https://azure.microsoft.com/dif/hub/"
            },
            {
                "id": "#test2",
                "type": "xdi",
                "serviceEndpoint": "https://xdi03-at.danubeclouds.com/cl/"
            }
        ]
```
2. @codeglobally can probably better answer this question as he is the main/only contributor to that repo, but judging from the last commit message in Feb 2, looks like it is up to date.
3. I guess any mainnet DID is a good DID. e.g. `did:ion:EiD3DIbDgBCajj2zCkE48x74FKTV9_Dcu1u_imzZddDKfg`

I am going to close the issue on the sidetree github page since this is more of an ION question.

**Comment by peacekeeper** [comment]
Thanks @thehenrytsai this makes sense!

Quick follow-up question, are you aware of any publicly hosted ION resolver endpoints that can resolve testnet DIDs?

**Comment by thehenrytsai** [comment]
Hi @peacekeeper,

Microsoft does run a testnet ION node at `https://dev.discover.did.msidentity.com, but to be clear this is intended mainly for its testing and development (as testnet implies) and is not subject to SLA promises like the mainnet node. It does resolve the test DID that you enquired about above.

**Comment by thehenrytsai** [comment]
Closing, feel free to open new issues as needed.
