### ISSUE TITLE
Question. How can I upload DID request object to Bitcoin testnet?

### ISSUE THREAD

**Issue by y8ncastle** [decentralized-identity/ion#197]
Hello, it's the first time that I've used Microsoft ION and I followed all of the instructions with https://identity.foundation/ion/install-guide/.

But after all, I can not use ION well. I only tested with console.html which is only for local to make JWS, Short-Form DID URI, Long-Form DID URI and Create DID Request Object in ion-tools repository.

This time, I want to generate my own DID object on Bitcoin testnet and check in ION Network explorer whether it is published well or not but I don't know how can I send a transaction with DID object to ION network. I think after the guide #8 in install-guide, there is no additional information about how to make a DID object and send it to ION network.

I guess because I'm a beginner of Bitcoin network or DID system, but I'm wondering how can I make a DID create request to ION network based on Bitcoin testnet, not locally.

I'm operating the Bitcoin core testnet in my computer and have synchronized it already by the way.

**Comment by thehenrytsai** [comment]
Hi @y8ncastle, if you are trying to submit the request to your local node, you will need to make sure:

1. You have testnet BTC to spend to write to Bitcoin testnet.
2. Your IPFS node is reachable externally (since people would need to fetch your ION data initially before it is replicated in multiple nodes), this typically involves opening  up specific port (4001) in your router.
3. Send a create DID request to your local node (localhost:3000)
4. The specification to craft the DID create operation request can be found at https://identity.foundation/sidetree/api/#create, however I expect manually crafting a request conforming to the spec can be challenging because it involves you creating keys, I'd recommend that you use the [ION SDK](https://github.com/decentralized-identity/ion-sdk/blob/main/tests/IonRequest.spec.ts#L7) to create the request, it would be much easier, assuming you know JavaScript/TypeScript.

**Comment by y8ncastle** [comment]
Thank you so much for your kind and detailed reply! I'll try with that :)
