### ISSUE TITLE
No rpcpassword set - using random cookie authentication.

### ISSUE THREAD

**Issue by dbolser** [decentralized-identity/ion#36]
Hi, is it possible to use cookie based instead of rpcpassword based authentication?

**Comment by thehenrytsai** [comment]
Cookie based authentication is currently not implemented because provides read-only access to only the user that starts the Bitcoin Core as described [here](https://github.com/bitcoin/bitcoin/blob/master/doc/JSON-RPC-interface.md), but the current microservice architecture allows the Sidetree Bitcoin service and Bitcoin Core to be hosted on different machines/networks.

Feel free to file a feature request directly at the Sidetree repo if this continues to be a blocker.

**Comment by dbolser** [comment]
Ahh, I see what you're saying. Sorry for showing my noobs, but where is the sidetree repo?

**Comment by dbolser** [comment]
Ignore me:
https://github.com/decentralized-identity/sidetree
