### ISSUE TITLE
How to register new DID using ion?

### ISSUE THREAD

**Issue by AnkitAtmecs** [decentralized-identity/ion#40]
We are trying to setup identity hub where we are planing to register  a new DID for performing read write operation. identity hub is using `_https://beta.hub.microsoft.com/_` as hub end point but we want to use the ION setup as the hub-end-point which is running on `_http://localhost:3000/_`.
Now i have two challenges in ION:
a) how to register a new DID ?
b) how to get ION hub end point?

**Comment by thehenrytsai** [comment]
Hi @AnkitAtmecs,

You should be able to use the [create API](https://github.com/decentralized-identity/sidetree/blob/master/docs/protocol.md#did-and-did-document-creation) specified in the protocol documentation to register new DIDs. Keep in mind that you obviously need to have enough funds in your bitcoin wallet in order to write to the blockchain.

For the hub endpoint, you can add the URI in the `serviceEndpoint` property in the DID document submitted in the create request.

**Comment by thehenrytsai** [comment]
Closing. Feel free to reopen if issue persists.

**Comment by AnthonyRonning** [comment]
Having a problem creating a DID using the API. I'm following the instructions and have this CURL request as follows: 

```
curl --location --request POST 'http://localhost:3000/' \
--header 'Content-Type: application/json' \
--data-raw '{
  "type": "create",
  "suffixData": {
	  "operationDataHash": "4472d99bba1670457ee9a6746e481edf488a2c55",
	  "recoveryKey": {
	    "publicKeyHex": "02f49802fb3e09c6dd43f19aa41293d1e0dad044b68cf81cf7079499edfd0aa9f1"
	  },
	  "nextRecoveryOtpHash": "a665a45920422f9d417e4867efdc4fb8a04a1f3fff1fa07e998e86f7f7a27ae3"
	},
  "operationData": {
	    "nextUpdateOtpHash": "a665a45920422f9d417e4867efdc4fb8a04a1f3fff1fa07e998e86f7f7a27ae3",
	    "document": {
		  "publicKey": [
		    {
		      "id": "#key1",
		      "type": "Secp256k1VerificationKey2018",
		      "publicKeyHex": "02f49802fb3e09c6dd43f19aa41293d1e0dad044b68cf81cf7079499edfd0aa9f1",
		      "usage": "signing"
		    }
		  ]
		}
	}
}'
```

Getting a `Bad request: TypeError: Cannot read property 'toString' of undefined` during `const response = await sidetreeCore.handleOperationRequest(ctx.body);`
