### ISSUE TITLE
Note in install doc the need for possible env var for Bitcoin

### ISSUE THREAD

**Issue by csuwildcat** [decentralized-identity/ion#75]

**Comment by k9ert** [comment]
Is that this one?
`Environment variable ION_BITCOIN_CONFIG_FILE_PATH undefined, using default path ../json/testnet-bitcoin-config.json instead.`

The default is confusing because it's not clear from which subdirectory that path is relative to. Usually it's the project's root but that doesn't seem to be the case here.
And it doesn't seem to be necessary to change the default?!

**Comment by mburns** [comment]
I believe I was bitten by this.

When I configured the `json/mainnet-*-*.json` files per the Install Guide, then I run the `ion-bitcoin` service, since `ION_BITCOIN_CONFIG_FILE_PATH` is unset it ignores my edited mainnet configs and instead uses the (default, invalid) testnet configs.

This results in a 'non-base58' failure because of this value being incorrectly used: https://github.com/decentralized-identity/ion/blob/master/json/testnet-bitcoin-config.json#L8

**Comment by csuwildcat** [comment]
I think this is helpful, because if many people overlook this or don't fully understand the behavior that will occur when this value is omitted, they will face the same situation. I would love to have a note in the Guide about this - would you like to take a swing at a PR that adds this informational text?

**Comment by mburns** [comment]
sure, let me see what I can come up with.
